

/* this ALWAYS GENERATED file contains the proxy stub code */


 /* File created by MIDL compiler version 7.00.0555 */
/* at Thu Dec 26 10:05:45 2019
 */
/* Compiler settings for PlugAlgo.idl:
    Oicf, W1, Zp8, env=Win32 (32b run), target_arch=X86 7.00.0555 
    protocol : dce , ms_ext, c_ext, robust
    error checks: allocation ref bounds_check enum stub_data 
    VC __declspec() decoration level: 
         __declspec(uuid()), __declspec(selectany), __declspec(novtable)
         DECLSPEC_UUID(), MIDL_INTERFACE()
*/
/* @@MIDL_FILE_HEADING(  ) */

#if !defined(_M_IA64) && !defined(_M_AMD64)


#pragma warning( disable: 4049 )  /* more than 64k source lines */
#if _MSC_VER >= 1200
#pragma warning(push)
#endif

#pragma warning( disable: 4211 )  /* redefine extern to static */
#pragma warning( disable: 4232 )  /* dllimport identity*/
#pragma warning( disable: 4024 )  /* array to pointer mapping*/
#pragma warning( disable: 4152 )  /* function/data pointer conversion in expression */
#pragma warning( disable: 4100 ) /* unreferenced arguments in x86 call */

#pragma optimize("", off ) 

#define USE_STUBLESS_PROXY


/* verify that the <rpcproxy.h> version is high enough to compile this file*/
#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif


#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error this stub requires an updated version of <rpcproxy.h>
#endif /* __RPCPROXY_H_VERSION__ */


#include "PlugAlgo_i.h"

#define TYPE_FORMAT_STRING_SIZE   3                                 
#define PROC_FORMAT_STRING_SIZE   1                                 
#define EXPR_FORMAT_STRING_SIZE   1                                 
#define TRANSMIT_AS_TABLE_SIZE    0            
#define WIRE_MARSHAL_TABLE_SIZE   0            

typedef struct _PlugAlgo_MIDL_TYPE_FORMAT_STRING
    {
    short          Pad;
    unsigned char  Format[ TYPE_FORMAT_STRING_SIZE ];
    } PlugAlgo_MIDL_TYPE_FORMAT_STRING;

typedef struct _PlugAlgo_MIDL_PROC_FORMAT_STRING
    {
    short          Pad;
    unsigned char  Format[ PROC_FORMAT_STRING_SIZE ];
    } PlugAlgo_MIDL_PROC_FORMAT_STRING;

typedef struct _PlugAlgo_MIDL_EXPR_FORMAT_STRING
    {
    long          Pad;
    unsigned char  Format[ EXPR_FORMAT_STRING_SIZE ];
    } PlugAlgo_MIDL_EXPR_FORMAT_STRING;


static const RPC_SYNTAX_IDENTIFIER  _RpcTransferSyntax = 
{{0x8A885D04,0x1CEB,0x11C9,{0x9F,0xE8,0x08,0x00,0x2B,0x10,0x48,0x60}},{2,0}};


extern const PlugAlgo_MIDL_TYPE_FORMAT_STRING PlugAlgo__MIDL_TypeFormatString;
extern const PlugAlgo_MIDL_PROC_FORMAT_STRING PlugAlgo__MIDL_ProcFormatString;
extern const PlugAlgo_MIDL_EXPR_FORMAT_STRING PlugAlgo__MIDL_ExprFormatString;


extern const MIDL_STUB_DESC Object_StubDesc;


extern const MIDL_SERVER_INFO IPlugAlgo_ServerInfo;
extern const MIDL_STUBLESS_PROXY_INFO IPlugAlgo_ProxyInfo;


extern const MIDL_STUB_DESC Object_StubDesc;


extern const MIDL_SERVER_INFO ISelfLearning_ServerInfo;
extern const MIDL_STUBLESS_PROXY_INFO ISelfLearning_ProxyInfo;



#if !defined(__RPC_WIN32__)
#error  Invalid build platform for this stub.
#endif

#if !(TARGET_IS_NT50_OR_LATER)
#error You need Windows 2000 or later to run this stub because it uses these features:
#error   /robust command line switch.
#error However, your C/C++ compilation flags indicate you intend to run this app on earlier systems.
#error This app will fail with the RPC_X_WRONG_STUB_VERSION error.
#endif


static const PlugAlgo_MIDL_PROC_FORMAT_STRING PlugAlgo__MIDL_ProcFormatString =
    {
        0,
        {

			0x0
        }
    };

static const PlugAlgo_MIDL_TYPE_FORMAT_STRING PlugAlgo__MIDL_TypeFormatString =
    {
        0,
        {
			NdrFcShort( 0x0 ),	/* 0 */

			0x0
        }
    };


/* Object interface: IUnknown, ver. 0.0,
   GUID={0x00000000,0x0000,0x0000,{0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46}} */


/* Object interface: IDispatch, ver. 0.0,
   GUID={0x00020400,0x0000,0x0000,{0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46}} */


/* Object interface: IPlugAlgo, ver. 0.0,
   GUID={0xAECCBEBA,0x779E,0x47E3,{0xA8,0xA8,0x3C,0x2C,0xB7,0x39,0x0D,0x90}} */

#pragma code_seg(".orpc")
static const unsigned short IPlugAlgo_FormatStringOffsetTable[] =
    {
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1
    };

static const MIDL_STUBLESS_PROXY_INFO IPlugAlgo_ProxyInfo =
    {
    &Object_StubDesc,
    PlugAlgo__MIDL_ProcFormatString.Format,
    &IPlugAlgo_FormatStringOffsetTable[-3],
    0,
    0,
    0
    };


static const MIDL_SERVER_INFO IPlugAlgo_ServerInfo = 
    {
    &Object_StubDesc,
    0,
    PlugAlgo__MIDL_ProcFormatString.Format,
    &IPlugAlgo_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0};
CINTERFACE_PROXY_VTABLE(664) _IPlugAlgoProxyVtbl = 
{
    &IPlugAlgo_ProxyInfo,
    &IID_IPlugAlgo,
    IUnknown_QueryInterface_Proxy,
    IUnknown_AddRef_Proxy,
    IUnknown_Release_Proxy ,
    0 /* IDispatch::GetTypeInfoCount */ ,
    0 /* IDispatch::GetTypeInfo */ ,
    0 /* IDispatch::GetIDsOfNames */ ,
    0 /* IDispatch_Invoke_Proxy */ ,
    0 /* IPlugAlgo::SetCurrentImage */ ,
    0 /* IPlugAlgo::GetRegion */ ,
    0 /* IPlugAlgo::GetErrorRegion */ ,
    0 /* IPlugAlgo::GetInternalStats */ ,
    0 /* IPlugAlgo::ReloadExternalFile */ ,
    0 /* IPlugAlgo::CenterLocationAlgo */ ,
    0 /* IPlugAlgo::CenterLocationAlgoHelp */ ,
    0 /* IPlugAlgo::CenterLocationAlgo1 */ ,
    0 /* IPlugAlgo::CenterLocationAlgo1Help */ ,
    0 /* IPlugAlgo::CenterLocationAlgoHS */ ,
    0 /* IPlugAlgo::CenterLocationAlgoHSHelp */ ,
    0 /* IPlugAlgo::CenterRelocationAlgoHS1 */ ,
    0 /* IPlugAlgo::CenterRelocationAlgoHS1Help */ ,
    0 /* IPlugAlgo::MatchingParaAlgo */ ,
    0 /* IPlugAlgo::MatchingParaAlgoHelp */ ,
    0 /* IPlugAlgo::CircleRegionLocationAlgo */ ,
    0 /* IPlugAlgo::CircleRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::DetectRegionLocationAlgo */ ,
    0 /* IPlugAlgo::DetectRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::ImageCenterLocationAlgo */ ,
    0 /* IPlugAlgo::ImageCenterLocationAlgoHelp */ ,
    0 /* IPlugAlgo::GetCurrentLocationXY */ ,
    0 /* IPlugAlgo::CurlOptimizeAlgo */ ,
    0 /* IPlugAlgo::CurlOptimizeAlgoHelp */ ,
    0 /* IPlugAlgo::UVCurlAlgo */ ,
    0 /* IPlugAlgo::UVCurlAlgoHelp */ ,
    0 /* IPlugAlgo::CurlNoCompoundAlgo */ ,
    0 /* IPlugAlgo::CurlNoCompoundAlgoHelp */ ,
    0 /* IPlugAlgo::DynThresholdAlgo */ ,
    0 /* IPlugAlgo::DynThresholdAlgoHelp */ ,
    0 /* IPlugAlgo::BubbleDetectProfileAlgo */ ,
    0 /* IPlugAlgo::BubbleDetectProfileAlgoHelp */ ,
    0 /* IPlugAlgo::AnnularRotaDynThresholdAlgo */ ,
    0 /* IPlugAlgo::AnnularRotaDynThresholdAlgoHelp */ ,
    0 /* IPlugAlgo::BlackDetectExcludeEdgesAlgo */ ,
    0 /* IPlugAlgo::BlackDetectExcludeEdgesAlgoHelp */ ,
    0 /* IPlugAlgo::BlackDetectAlgo */ ,
    0 /* IPlugAlgo::BlackDetectAlgoHelp */ ,
    0 /* IPlugAlgo::EdgeAlgo */ ,
    0 /* IPlugAlgo::EdgeAlgoHelp */ ,
    0 /* IPlugAlgo::LineDetectionAlgo */ ,
    0 /* IPlugAlgo::LineDetectionAlgoHelp */ ,
    0 /* IPlugAlgo::FilmHairDetectAlgo */ ,
    0 /* IPlugAlgo::FilmHairDetectAlgoHelp */ ,
    0 /* IPlugAlgo::SetCurrentTaskName */ ,
    0 /* IPlugAlgo::MatchingParaMinScoreAlgo */ ,
    0 /* IPlugAlgo::MatchingParaMinScoreAlgoHelp */ ,
    0 /* IPlugAlgo::BlackDetectUseUpSizeAlgo */ ,
    0 /* IPlugAlgo::BlackDetectUseUpSizeAlgoHelp */ ,
    0 /* IPlugAlgo::DerivateGaussDetectAlgo */ ,
    0 /* IPlugAlgo::DerivateGaussDetectAlgoHelp */ ,
    0 /* IPlugAlgo::TotalHeightMeasureAlgo */ ,
    0 /* IPlugAlgo::TotalHeightMeasureAlgoHelp */ ,
    0 /* IPlugAlgo::CrownHeightMeasureAlgo */ ,
    0 /* IPlugAlgo::CrownHeightMeasureAlgoHelp */ ,
    0 /* IPlugAlgo::DiameterMeasureAlgo */ ,
    0 /* IPlugAlgo::DiameterMeasureAlgoHelp */ ,
    0 /* IPlugAlgo::BarLocationAlgo */ ,
    0 /* IPlugAlgo::BarLocationAlgoHelp */ ,
    0 /* IPlugAlgo::RegionLocationByModelTool */ ,
    0 /* IPlugAlgo::RegionLocationByModelToolHelp */ ,
    0 /* IPlugAlgo::CenterReLocationAlgo2 */ ,
    0 /* IPlugAlgo::CenterReLocationAlgo2Help */ ,
    0 /* IPlugAlgo::SideCenterLocationAlgo */ ,
    0 /* IPlugAlgo::SideCenterLocationAlgoHelp */ ,
    0 /* IPlugAlgo::NeckBaseEdgeDetectAlgo */ ,
    0 /* IPlugAlgo::NeckBaseEdgeDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D13_SideTopRegAngleDetectAlgo */ ,
    0 /* IPlugAlgo::D13_SideTopRegAngleDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D13_PlatformDetectAlgo */ ,
    0 /* IPlugAlgo::D13_PlatformDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D13_SlopEdgeDetectAlgo */ ,
    0 /* IPlugAlgo::D13_SlopEdgeDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D13_SideSlopRegionLocationAlgo */ ,
    0 /* IPlugAlgo::D13_SideSlopRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::D13_TriangleDetectAlgo */ ,
    0 /* IPlugAlgo::D13_TriangleDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D13_NeckRegionLocationAlgo */ ,
    0 /* IPlugAlgo::D13_NeckRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::SealingFaceRegionLocationAlgo */ ,
    0 /* IPlugAlgo::SealingFaceRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::ScrapEdgeDetectAlgo */ ,
    0 /* IPlugAlgo::ScrapEdgeDetectAlgoHelp */ ,
    0 /* IPlugAlgo::CrownRegionLocationAlgo */ ,
    0 /* IPlugAlgo::CrownRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::D13_TopAngleDetectAlgo */ ,
    0 /* IPlugAlgo::D13_TopAngleDetectAlgoHelp */ ,
    0 /* IPlugAlgo::AB20_TopRegDetectAlgo */ ,
    0 /* IPlugAlgo::AB20_TopRegDetectAlgoHelp */ ,
    0 /* IPlugAlgo::AB20_SlopEdgeDetectAlgo */ ,
    0 /* IPlugAlgo::AB20_SlopEdgeDetectAlgoHelp */ ,
    0 /* IPlugAlgo::AB20_SideSlopRegionLocationAlgo */ ,
    0 /* IPlugAlgo::AB20_SideSlopRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::AB20_NeckRegionLocationAlgo */ ,
    0 /* IPlugAlgo::AB20_NeckRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::D20_SideTopRegAngleDetectAlgo */ ,
    0 /* IPlugAlgo::D20_SideTopRegAngleDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D20_PlatformDetectAlgo */ ,
    0 /* IPlugAlgo::D20_PlatformDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D20_SlopEdgeDetectAlgo */ ,
    0 /* IPlugAlgo::D20_SlopEdgeDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D20_SideSlopRegionLocationAlgo */ ,
    0 /* IPlugAlgo::D20_SideSlopRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::D20_StripePatternDetectAlgo */ ,
    0 /* IPlugAlgo::D20_StripePatternDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D20_NeckRegionLocationAlgo */ ,
    0 /* IPlugAlgo::D20_NeckRegionLocationAlgoHelp */ ,
    0 /* IPlugAlgo::D20_TopAngleDetectAlgo */ ,
    0 /* IPlugAlgo::D20_TopAngleDetectAlgoHelp */ ,
    0 /* IPlugAlgo::D20_TopAngleDetectAlgo1 */ ,
    0 /* IPlugAlgo::D20_TopAngleDetectAlgo1Help */ ,
    0 /* IPlugAlgo::EccentricityDetectAlgo */ ,
    0 /* IPlugAlgo::EccentricityDetectAlgoHelp */ ,
    0 /* IPlugAlgo::BottomDotDetectAlgo */ ,
    0 /* IPlugAlgo::BottomDotDetectAlgoHelp */ ,
    0 /* IPlugAlgo::CrownCenterRelocationAlgo */ ,
    0 /* IPlugAlgo::CrownCenterRelocationAlgoHelp */ ,
    0 /* IPlugAlgo::ForkTotalHeightMeasureAlgo */ ,
    0 /* IPlugAlgo::ForkTotalHeightMeasureAlgoHelp */ ,
    0 /* IPlugAlgo::CrownHeightMeasureSAlgo */ ,
    0 /* IPlugAlgo::CrownHeightMeasureSAlgoHelp */ ,
    0 /* IPlugAlgo_SidePlatformRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_SidePlatformRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_WholeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D20_WholeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_StripePatternRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D20_StripePatternRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_TopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D20_TopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB20_WholeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB20_WholeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopInwallRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopInwallRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D13_WholeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D13_WholeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D13_TriangleRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D13_TriangleRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D13_TopAngleDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_D13_TopAngleDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_N_DynThresholdAlgo_Proxy */ ,
    0 /* IPlugAlgo_N_DynThresholdAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_NeckBaseEdgeDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_NeckBaseEdgeDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_G20_SideTopRegAngleDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_SideTopRegAngleDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_PlatformDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_PlatformDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_SlopEdgeDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_SlopEdgeDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_InWallRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_InWallRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_MiddleEdgeDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_MiddleEdgeDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_NeckRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_NeckRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_N_DerivateGaussDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_N_DerivateGaussDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_WholeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_WholeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_TopAngleDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_TopAngleDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_TopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_TopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BottomDotRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_BottomDotRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_CircleRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_CircleRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D13_InWallRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D13_InWallRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_NeckRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_NeckRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_TopSealingFaceRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_TopSealingFaceRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D13_DerivateGaussDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_D13_DerivateGaussDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_InWallDynThresholdAlgo_Proxy */ ,
    0 /* IPlugAlgo_InWallDynThresholdAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureAlgo1_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureAlgo1_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_ForkTotalHeightMeasureAlgo1_Proxy */ ,
    0 /* IPlugAlgo_ForkTotalHeightMeasureAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureSAlgo1_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureSAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_ScrapDiameterMeasureAlgo_Proxy */ ,
    0 /* IPlugAlgo_ScrapDiameterMeasureAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_CenterLocationAlgoM_Proxy */ ,
    0 /* IPlugAlgo_CenterLocationAlgoMHelp_Proxy */ ,
    0 /* IPlugAlgo_SealingFaceRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_SealingFaceRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRubberRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRubberRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D13_SideTopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D13_SideTopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_SideTopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D20_SideTopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_RubberDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_D20_RubberDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_SlopEdgeDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_D20_SlopEdgeDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D20_NeckRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_D20_NeckRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_GSurfaceAlgo_Proxy */ ,
    0 /* IPlugAlgo_GSurfaceAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_TopCenterDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_D20_TopCenterDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_TopRubberRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D20_TopRubberRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_TopSealingFaceRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_TopSealingFaceRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_WarpedMembraneDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_WarpedMembraneDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternCoordAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternCoordAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_SideSlopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_SideSlopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_CrownRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_CrownRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_SlotDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_SlotDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_OutEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_OutEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_DynThresholdForColorAlgo_Proxy */ ,
    0 /* IPlugAlgo_DynThresholdForColorAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_EdgeForColorAlgo_Proxy */ ,
    0 /* IPlugAlgo_EdgeForColorAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AnnularRotaDynThresholdForColorAlgo_Proxy */ ,
    0 /* IPlugAlgo_AnnularRotaDynThresholdForColorAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_TopSealingFaceEdgeDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_TopSealingFaceEdgeDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternSearchRegAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternSearchRegAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternDynThresholdAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternDynThresholdAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_N_BubbleDetectProfileAlgo_Proxy */ ,
    0 /* IPlugAlgo_N_BubbleDetectProfileAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_N_LineDetectionAlgo_Proxy */ ,
    0 /* IPlugAlgo_N_LineDetectionAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_TopSideLowRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_TopSideLowRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_DoubleFoldDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_DoubleFoldDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_MiddleEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_MiddleEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternDynThresholdAlgo1_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternDynThresholdAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_CrownCircleRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB20_CrownCircleRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_RegionLocationDiffByModelTool_Proxy */ ,
    0 /* IPlugAlgo_RegionLocationDiffByModelToolHelp_Proxy */ ,
    0 /* IPlugAlgo_WhiteDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_WhiteDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_MinMaxGrayDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_MinMaxGrayDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_CrownCenterRelocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_CrownCenterRelocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D13_TopAngleDetectAlgo11_Proxy */ ,
    0 /* IPlugAlgo_D13_TopAngleDetectAlgo11Help_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D13_PlatformDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_D13_PlatformDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D13_SideSlopRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_D13_SideSlopRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D13_SideTopRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_D13_SideTopRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D13_TriangleDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_D13_TriangleDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_D13_TopAngleDetectAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_TopAngleDetectAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_D13_TopCenterDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_D13_TopCenterDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRubberRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_TopRubberRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_TopSealingFaceRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_TopSealingFaceRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_D13_SideTopRegAngleDetectAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_SideTopRegAngleDetectAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_D13_SideSlopRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_SideSlopRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_D13_NeckRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_NeckRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_D13_PlatformDetectAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_PlatformDetectAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_D13_InWallRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_InWallRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_D13_SideTopRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_SideTopRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_D13_StripePatternDetectAlgo2_Proxy */ ,
    0 /* IPlugAlgo_D13_StripePatternDetectAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_T20_SideTopRegAngleDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_SideTopRegAngleDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_PlatformDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_PlatformDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_SideConeBiasDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_SideConeBiasDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_SlopEdgeDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_SlopEdgeDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_ConPatternCoordAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_ConPatternCoordAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_ConPatternSearchRegUpAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_ConPatternSearchRegUpAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_CirclePatternDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_CirclePatternDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_ConPatternSearchRegDownAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_ConPatternSearchRegDownAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_TrianglePatternDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_TrianglePatternDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_MiddleEdgeDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_MiddleEdgeDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_InWallRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_InWallRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_SideTopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_SideTopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_WholeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_WholeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_TopAngleDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_TopAngleDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_TopCenterDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_TopCenterDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_TopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_TopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_SideSlopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_SideSlopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_CirclePatternDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_T20_CirclePatternDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_T20_WholeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_WholeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_TopRubberRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_TopRubberRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_ABEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_ABEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternDetectProfileAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_ConPatternDetectProfileAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_SideTopRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_SideTopRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_ABEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_ABEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_SideTopEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_SideTopEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_CurlNoCompoundForColorAlgo_Proxy */ ,
    0 /* IPlugAlgo_CurlNoCompoundForColorAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_TopForkRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D20_TopForkRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_StripePatternDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_D20_StripePatternDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_T20_TopForkRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_TopForkRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_G20_NeckRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_G20_NeckRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_DownEdgeDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB20_DownEdgeDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_ScrapEdgeDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_ScrapEdgeDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_NeckRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_AB20_NeckRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_DownEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB20_DownEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB20_SideSlopRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_AB20_SideSlopRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopRegDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopRegDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopRegDetectAlgo2_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopRegDetectAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_BarLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_BarLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureAlgo2_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureAlgo2_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_DiameterMeasureAlgo2_Proxy */ ,
    0 /* IPlugAlgo_DiameterMeasureAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_HeightMeasureAlgo_Proxy */ ,
    0 /* IPlugAlgo_HeightMeasureAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_G20_EmbossCoordAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_EmbossCoordAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_EmbossSearchRegAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_EmbossSearchRegAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_NeckRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_G20_NeckRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_G20_MiddleEdgeRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_G20_MiddleEdgeRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_NeckRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_AB20_NeckRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_RubberMatScrapEdgeDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_RubberMatScrapEdgeDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_RubberMatRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_RubberMatRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_RubberDotRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_RubberDotRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AnnularRotaDynThresholdAlgoBW_Proxy */ ,
    0 /* IPlugAlgo_AnnularRotaDynThresholdAlgoBWHelp_Proxy */ ,
    0 /* IPlugAlgo_SetSelfLearningParam_Proxy */ ,
    0 /* IPlugAlgo_SelectModelImage_Proxy */ ,
    0 /* IPlugAlgo_DeleteModelImage_Proxy */ ,
    0 /* IPlugAlgo_SaveResult_Proxy */ ,
    0 /* IPlugAlgo_AddModelImage_Proxy */ ,
    0 /* IPlugAlgo_GetSelfLearningResult_Proxy */ ,
    0 /* IPlugAlgo_ResetSelfLearningRegion_Proxy */ ,
    0 /* IPlugAlgo_GetSelfLearningRegion_Proxy */ ,
    0 /* IPlugAlgo_ResetSelfLearningProcedure_Proxy */ ,
    0 /* IPlugAlgo_SetSelfLearningTargetTaskName_Proxy */ ,
    0 /* IPlugAlgo_DetectSmalCircleAngle_Proxy */ ,
    0 /* IPlugAlgo_DetectSmalCircleAngleHelp_Proxy */ ,
    0 /* IPlugAlgo_AB32_InnerWallRegDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB32_InnerWallRegDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB32_SideSlopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB32_SideSlopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_NeckBaseEdgeDetectAlgo2_Proxy */ ,
    0 /* IPlugAlgo_NeckBaseEdgeDetectAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_DiameterMeasureAlgo3_Proxy */ ,
    0 /* IPlugAlgo_DiameterMeasureAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureAlgo3_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureAlgo3_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_AB32_NeckRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB32_NeckRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_TopDefectDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_TopDefectDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_TopRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_G20_TopRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_SideSlopRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_AB20_SideSlopRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_FilmOrNotDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB20_FilmOrNotDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_CountValueNumberAlgo_Proxy */ ,
    0 /* IPlugAlgo_CountValueNumberAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_FilmEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_FilmEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_DerivateDynThresholdAlgo_Proxy */ ,
    0 /* IPlugAlgo_DerivateDynThresholdAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_DerivateGaussDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_DerivateGaussDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_LineDetectionAlgo1_Proxy */ ,
    0 /* IPlugAlgo_LineDetectionAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_FilmBigErrorDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB20_FilmBigErrorDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BarLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_BarLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopGlueDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopGlueDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BottomDotRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_BottomDotRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckCornerRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckCornerRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_T20_StripePatternRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_TopSealingFaceRegionLocationAlgo3_Proxy */ ,
    0 /* IPlugAlgo_TopSealingFaceRegionLocationAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_GetWhiteErrorRegion_Proxy */ ,
    0 /* IPlugAlgo_GetInterImgs_Proxy */ ,
    0 /* IPlugAlgo_T20_TopLessRubberDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_TopLessRubberDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckRegionLocationAlgo3_Proxy */ ,
    0 /* IPlugAlgo_T20_NeckRegionLocationAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_DynThresholdAlgo1_Proxy */ ,
    0 /* IPlugAlgo_DynThresholdAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeDetectAlgo2_Proxy */ ,
    0 /* IPlugAlgo_G20_DownEdgeDetectAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_DownEdgeDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_AB20_DownEdgeDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_NeckBaseEdgeDetectAlgo3_Proxy */ ,
    0 /* IPlugAlgo_NeckBaseEdgeDetectAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_AnnularRotaDynThresholdAlgo1_Proxy */ ,
    0 /* IPlugAlgo_AnnularRotaDynThresholdAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_FilmOrNotDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_AB20_FilmOrNotDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureAlgo33_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureAlgo33Help_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureAlgo33_Proxy */ ,
    0 /* IPlugAlgo_CrownHeightMeasureAlgo33Help_Proxy */ ,
    0 /* IPlugAlgo_BottomDotRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_BottomDotRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_SideSlopRegionLocationAlgo3_Proxy */ ,
    0 /* IPlugAlgo_AB20_SideSlopRegionLocationAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_BottomDotRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB20_BottomDotRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_SealingFaceRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_SealingFaceRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopGlueDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_AB20_TopGlueDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_TopBaseLineDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_TopBaseLineDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_TopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_TopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_SideCenterLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_SideCenterLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_LineDetectFromBaseTopAlgo_Proxy */ ,
    0 /* IPlugAlgo_LineDetectFromBaseTopAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_TopEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_TopEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_MiddleEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_MiddleEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_MiddleRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_MiddleRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_LineDetectFromBaseDownAlgo_Proxy */ ,
    0 /* IPlugAlgo_LineDetectFromBaseDownAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_DownEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_DownEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BottomRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_BottomRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_WholeRegionLocationForHelixAlgo_Proxy */ ,
    0 /* IPlugAlgo_WholeRegionLocationForHelixAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BarLocationAlgo3_Proxy */ ,
    0 /* IPlugAlgo_BarLocationAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_T20_TopCircleLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_T20_TopCircleLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_DerivateGaussDetectForAnnulusAlgo_Proxy */ ,
    0 /* IPlugAlgo_DerivateGaussDetectForAnnulusAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB32_BottomRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB32_BottomRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB32_TopInwallRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB32_TopInwallRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB32_TopHighLightRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB32_TopHighLightRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_DerivateGaussDetectFreeModelAlgo_Proxy */ ,
    0 /* IPlugAlgo_DerivateGaussDetectFreeModelAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BubbleDetectProfileForColorAlgo_Proxy */ ,
    0 /* IPlugAlgo_BubbleDetectProfileForColorAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_ABEdgeRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_ABEdgeRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB20_NeckRegionLocationAlgo3_Proxy */ ,
    0 /* IPlugAlgo_AB20_NeckRegionLocationAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_AB32_DownEdgeDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB32_DownEdgeDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_F20_SideTopRegAngleDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_F20_SideTopRegAngleDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_F20_PlatformDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_F20_PlatformDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_F20_SideTopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_F20_SideTopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_F20_OutInWallRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_F20_OutInWallRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_F20_TopAngleDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_F20_TopAngleDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_RegionLocationByModelTool1_Proxy */ ,
    0 /* IPlugAlgo_RegionLocationByModelTool1Help_Proxy */ ,
    0 /* IPlugAlgo_F20_TopRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_F20_TopRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_F20_StripePatternDetectAlgo_Proxy */ ,
    0 /* IPlugAlgo_F20_StripePatternDetectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_SideTopHighLightRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_SideTopHighLightRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BottomCharacterLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_BottomCharacterLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BottomCharacterRegionAlgo_Proxy */ ,
    0 /* IPlugAlgo_BottomCharacterRegionAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB32_DownEdgeDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_AB32_DownEdgeDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_ABEdgeRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_ABEdgeRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_ABEdgeRegionLocationAlgo3_Proxy */ ,
    0 /* IPlugAlgo_ABEdgeRegionLocationAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_NeckBaseEdgeDetectFreeModelAlgo_Proxy */ ,
    0 /* IPlugAlgo_NeckBaseEdgeDetectFreeModelAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB32_TopHighLightRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_AB32_TopHighLightRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB32_BottomBorderRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB32_BottomBorderRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_DoubleFoldDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_DoubleFoldDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_AB32_DownEdgeDetectAlgo2_Proxy */ ,
    0 /* IPlugAlgo_AB32_DownEdgeDetectAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_SidePlatformRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_SidePlatformRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_SideNeckBorderRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_SideNeckBorderRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_D20_SideInwallRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_D20_SideInwallRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureInjectorAlgo_Proxy */ ,
    0 /* IPlugAlgo_TotalHeightMeasureInjectorAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_WarpedMembraneDetectAlgo1_Proxy */ ,
    0 /* IPlugAlgo_WarpedMembraneDetectAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_SideTopSectorRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_SideTopSectorRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AngleSelectAlgo_Proxy */ ,
    0 /* IPlugAlgo_AngleSelectAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BottomCharacterLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_BottomCharacterLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_BottomDotRegionLocationAlgo3_Proxy */ ,
    0 /* IPlugAlgo_BottomDotRegionLocationAlgo3Help_Proxy */ ,
    0 /* IPlugAlgo_LineDetectionAlgo2_Proxy */ ,
    0 /* IPlugAlgo_LineDetectionAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_DerivateGaussDetectForAnnulusAlgo1_Proxy */ ,
    0 /* IPlugAlgo_DerivateGaussDetectForAnnulusAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_BubbleDetectProfileForColorFilmAlgo_Proxy */ ,
    0 /* IPlugAlgo_BubbleDetectProfileForColorFilmAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_DynThresholdForColorFilmAlgo_Proxy */ ,
    0 /* IPlugAlgo_DynThresholdForColorFilmAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_AB32_BottomEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_AB32_BottomEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_FilmEdgeRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_FilmEdgeRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_InWallDynThresholdAlgo1_Proxy */ ,
    0 /* IPlugAlgo_InWallDynThresholdAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_SealingEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_SealingEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_TopCornerLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_TopCornerLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_TopForkEdgeRegionLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_TopForkEdgeRegionLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_TopHLightLocationAlgo_Proxy */ ,
    0 /* IPlugAlgo_G20_TopHLightLocationAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BubbleDetectProfileForAnnulusAlgo_Proxy */ ,
    0 /* IPlugAlgo_BubbleDetectProfileForAnnulusAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_G20_TopRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_G20_TopRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_G20_InWallRegionLocationAlgo1_Proxy */ ,
    0 /* IPlugAlgo_G20_InWallRegionLocationAlgo1Help_Proxy */ ,
    0 /* IPlugAlgo_GLineAlgo_Proxy */ ,
    0 /* IPlugAlgo_GLineAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_ScrapEdgeDetectAlgo2_Proxy */ ,
    0 /* IPlugAlgo_ScrapEdgeDetectAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_G20_InWallRegionLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_G20_InWallRegionLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_CenterLocationRightOrNotAlgo_Proxy */ ,
    0 /* IPlugAlgo_CenterLocationRightOrNotAlgoHelp_Proxy */ ,
    0 /* IPlugAlgo_BottomCharacterLocationAlgo2_Proxy */ ,
    0 /* IPlugAlgo_BottomCharacterLocationAlgo2Help_Proxy */ ,
    0 /* IPlugAlgo_SideCenterLocationAlgoForColor_Proxy */ ,
    0 /* IPlugAlgo_SideCenterLocationAlgoForColorHelp_Proxy */ ,
    0 /* IPlugAlgo_AnnularRotaDynThresholdForColorAlgoBW_Proxy */ ,
    0 /* IPlugAlgo_AnnularRotaDynThresholdForColorAlgoBWHelp_Proxy */
};


static const PRPC_STUB_FUNCTION IPlugAlgo_table[] =
{
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION
};

CInterfaceStubVtbl _IPlugAlgoStubVtbl =
{
    &IID_IPlugAlgo,
    &IPlugAlgo_ServerInfo,
    664,
    &IPlugAlgo_table[-3],
    CStdStubBuffer_DELEGATING_METHODS
};


/* Object interface: ISelfLearning, ver. 0.0,
   GUID={0xFFACCB7D,0x68BF,0x4C20,{0x9C,0x56,0x0E,0xDB,0xDD,0xE7,0x3B,0xFD}} */

#pragma code_seg(".orpc")
static const unsigned short ISelfLearning_FormatStringOffsetTable[] =
    {
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1,
    (unsigned short) -1
    };

static const MIDL_STUBLESS_PROXY_INFO ISelfLearning_ProxyInfo =
    {
    &Object_StubDesc,
    PlugAlgo__MIDL_ProcFormatString.Format,
    &ISelfLearning_FormatStringOffsetTable[-3],
    0,
    0,
    0
    };


static const MIDL_SERVER_INFO ISelfLearning_ServerInfo = 
    {
    &Object_StubDesc,
    0,
    PlugAlgo__MIDL_ProcFormatString.Format,
    &ISelfLearning_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0};
CINTERFACE_PROXY_VTABLE(13) _ISelfLearningProxyVtbl = 
{
    &ISelfLearning_ProxyInfo,
    &IID_ISelfLearning,
    IUnknown_QueryInterface_Proxy,
    IUnknown_AddRef_Proxy,
    IUnknown_Release_Proxy ,
    0 /* ISelfLearning::SetSelfLearningParam */ ,
    0 /* ISelfLearning::SelectModelImage */ ,
    0 /* ISelfLearning::DeleteModelImage */ ,
    0 /* ISelfLearning::SaveResult */ ,
    0 /* ISelfLearning::AddModelImage */ ,
    0 /* ISelfLearning::GetSelfLearningResult */ ,
    0 /* ISelfLearning::ResetSelfLearningRegion */ ,
    0 /* ISelfLearning::GetSelfLearningRegion */ ,
    0 /* ISelfLearning::ResetSelfLearningProcedure */ ,
    0 /* ISelfLearning::SetSelfLearningTargetTaskName */
};

const CInterfaceStubVtbl _ISelfLearningStubVtbl =
{
    &IID_ISelfLearning,
    &ISelfLearning_ServerInfo,
    13,
    0, /* pure interpreted */
    CStdStubBuffer_METHODS
};

static const MIDL_STUB_DESC Object_StubDesc = 
    {
    0,
    NdrOleAllocate,
    NdrOleFree,
    0,
    0,
    0,
    0,
    0,
    PlugAlgo__MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x700022b, /* MIDL Version 7.0.555 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    0x1, /* MIDL flag */
    0, /* cs routines */
    0,   /* proxy/server info */
    0
    };

const CInterfaceProxyVtbl * const _PlugAlgo_ProxyVtblList[] = 
{
    ( CInterfaceProxyVtbl *) &_ISelfLearningProxyVtbl,
    ( CInterfaceProxyVtbl *) &_IPlugAlgoProxyVtbl,
    0
};

const CInterfaceStubVtbl * const _PlugAlgo_StubVtblList[] = 
{
    ( CInterfaceStubVtbl *) &_ISelfLearningStubVtbl,
    ( CInterfaceStubVtbl *) &_IPlugAlgoStubVtbl,
    0
};

PCInterfaceName const _PlugAlgo_InterfaceNamesList[] = 
{
    "ISelfLearning",
    "IPlugAlgo",
    0
};

const IID *  const _PlugAlgo_BaseIIDList[] = 
{
    0,
    &IID_IDispatch,
    0
};


#define _PlugAlgo_CHECK_IID(n)	IID_GENERIC_CHECK_IID( _PlugAlgo, pIID, n)

int __stdcall _PlugAlgo_IID_Lookup( const IID * pIID, int * pIndex )
{
    IID_BS_LOOKUP_SETUP

    IID_BS_LOOKUP_INITIAL_TEST( _PlugAlgo, 2, 1 )
    IID_BS_LOOKUP_RETURN_RESULT( _PlugAlgo, 2, *pIndex )
    
}

const ExtendedProxyFileInfo PlugAlgo_ProxyFileInfo = 
{
    (PCInterfaceProxyVtblList *) & _PlugAlgo_ProxyVtblList,
    (PCInterfaceStubVtblList *) & _PlugAlgo_StubVtblList,
    (const PCInterfaceName * ) & _PlugAlgo_InterfaceNamesList,
    (const IID ** ) & _PlugAlgo_BaseIIDList,
    & _PlugAlgo_IID_Lookup, 
    2,
    2,
    0, /* table of [async_uuid] interfaces */
    0, /* Filler1 */
    0, /* Filler2 */
    0  /* Filler3 */
};
#pragma optimize("", on )
#if _MSC_VER >= 1200
#pragma warning(pop)
#endif


#endif /* !defined(_M_IA64) && !defined(_M_AMD64)*/

